---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: odh-notebook-controller-webhook-cert
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
  selector:
    app: odh-notebook-controller-webhook
    app.kubernetes.io/part-of: odh-notebook-controller
    component.opendatahub.io/name: odh-notebook-controller-webhook
    kustomize.component: odh-notebook-controller-webhook
    opendatahub.io/component: 'true'